version: '3'

services:
  db:
    image: postgres:16
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    container_name: teslo-shop-db
    volumes:
      - ./postgres:/var/lib/postgresql/data
